name: LockedItem
version: 1.0.0
api: 3.21.2
main: ytbjero\LockedItem\LockedItem
author: ytbjero

commands:
  setlock:
    description: "Lock the item in your hand"
  unlock:
    description: "Unlock the item in your hand"
